### PR TITLE
Create Tea brew

### PR DESCRIPTION
**Pull request by unclecrypto7**

### CODE REVIEW

**Comment by iwahbe** [comment]
@unclecrypto7 Can you explain this PR?

**Comment by unclecrypto7** [comment]
> @unclecrypto7 Can you explain this PR?

For my oss project in tea protocol project im search your project and use your project to conecting in tea protocol @iwahbe

**Comment by iwahbe** [comment]
@unclecrypto7 I'm not part of the Tea project and I don't see how brew-rs is either. Can you find a way to consume brew-rs without injecting this file into the repo?

**Comment by unclecrypto7** [comment]
@iwahbe u not sign in tea protocol tesnet?
Why im see this project in tea protocol tesnet?
Just create repositoris with my filee and im inisitiv comit with u because if im only create repo this iis invalid..
Sory, if wrong but im want to completed the task, 
Can u help me sir?

**Comment by iwahbe** [comment]
> @iwahbe u not sign in tea protocol tesnet? Why im see this project in tea protocol tesnet? Just create repositoris with my filee and im inisitiv comit with u because if im only create repo this iis invalid.. Sory, if wrong but im want to completed the task, Can u help me sir?

I did not sign up for the Tea protocol. I had never heard about it until this PR. I'm not sure what your trying to do, but you will need to find a way to do it without putting this file into brew-rs.

**Pull request closed without merging**
